spring:
  redis:
    host: localhost
    port: 6379
  graphql:
    schema:
      location: classpath:/graphql/**/
    graphiql:
      enable: true
    websocket:
      path: /graphql
    cors:
      allowed-origins: http://localhost:19006
user:
  topic: sub:user:1
